export type PdlcErrorCode =
  | "INVALID_ARGUMENT"
  | "INVALID_RECORD_ID"
  | "RECORD_NOT_FOUND"
  | "CURRENT_RECORD_NOT_SET"
  | "REVISION_CONFLICT"
  | "LOCK_HELD"
  | "LOCK_OWNERSHIP_LOST"
  | "VALIDATION_FAILED"
  | "WORKFLOW_NOT_FOUND"
  | "DUPLICATE_WORKFLOW"
  | "JOURNEY_NOT_FOUND"
  | "DUPLICATE_JOURNEY"
  | "UNKNOWN_STAGE_REF"
  | "STAGE_NOT_FOUND"
  | "DUPLICATE_STAGE"
  | "CHECKPOINT_NOT_IMPLEMENTED"
  | "BUILD_NOT_READY"
  | "PORTABILITY_VIOLATION"
  | "PLUGIN_ROOT_NOT_FOUND"
  | "PLUGIN_MANIFEST_NOT_FOUND"
  | "PLUGIN_DESCRIPTOR_NOT_FOUND"
  | "PLUGIN_NAME_MISMATCH"
  | "UNSUPPORTED_PLUGIN_BINDINGS_SCHEMA"
  | "INVALID_PLUGIN_BINDINGS_DESCRIPTOR"
  | "INVALID_PLUGIN_BINDING"
  | "PLUGIN_STAGE_UNBOUND"
  | "DUPLICATE_PLUGIN_STAGE_BINDING"
  | "INVALID_PLUGIN_AGENT"
  | "PLUGIN_AGENT_NOT_FOUND"
  | "PLUGIN_SKILL_NOT_FOUND"
  | "PLUGIN_REQUIRED";

export class PdlcError extends Error {
  readonly code: PdlcErrorCode;
  readonly details?: unknown;

  constructor(code: PdlcErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = "PdlcError";
    this.code = code;
    this.details = details;
  }
}
