export type PdlcErrorCode =
  | "INVALID_ARGUMENT"
  | "INVALID_RECORD_ID"
  | "RECORD_NOT_FOUND"
  | "CURRENT_RECORD_NOT_SET"
  | "REVISION_CONFLICT"
  | "LOCK_HELD"
  | "LOCK_OWNERSHIP_LOST"
  | "VALIDATION_FAILED"
  | "DELIVERY_FLOW_NOT_FOUND"
  | "DELIVERY_FLOW_NOT_EXECUTABLE"
  | "DUPLICATE_DELIVERY_FLOW"
  | "UNKNOWN_STAGE_REF"
  | "STAGE_NOT_FOUND"
  | "DUPLICATE_STAGE"
  | "BUILD_NOT_READY"
  | "PORTABILITY_VIOLATION"
  | "DUPLICATE_DOMAIN_STAGE_HOOK"
  | "INVALID_DOMAIN_AGENT"
  | "INVALID_DOMAIN_HOOK"
  | "DOMAIN_AGENT_NOT_FOUND"
  | "DOMAIN_SKILL_NOT_FOUND"
  | "DOMAIN_FILE_CONFLICT"
  | "DUPLICATE_INTEGRATION"
  | "INTEGRATION_ID_MISMATCH"
  | "INTEGRATION_SKILL_NOT_FOUND"
  | "INTEGRATION_NOT_FOUND"
  | "CONTEXT_RESOLUTION_FAILED"
  | "CONTEXT_RECEIPT_INVALID"
  | "DUPLICATE_ROLE"
  | "UNKNOWN_ROLE_REF"
  | "ROLE_NOT_FOUND"
  | "ROLE_DEFINITION_NOT_FOUND"
  | "INVALID_ROLE_DEFINITION";

export class PdlcError extends Error {
  readonly code: PdlcErrorCode;
  readonly details?: unknown;

  constructor(code: PdlcErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = "PdlcError";
    this.code = code;
    this.details = details;
  }
}
