export type PdlcErrorCode =
  | "INVALID_ARGUMENT"
  | "INVALID_RECORD_ID"
  | "RECORD_NOT_FOUND"
  | "CURRENT_RECORD_NOT_SET"
  | "MULTIPLE_ACTIVE_RECORDS"
  | "ACTIVE_RECORD_EXISTS"
  | "INITIALIZATION_ROLLBACK_FAILED"
  | "STATE_AUDIT_PERSISTENCE_FAILED"
  | "STATE_AUDIT_ROLLBACK_FAILED"
  | "REVISION_CONFLICT"
  | "LOCK_HELD"
  | "LOCK_OWNERSHIP_LOST"
  | "VALIDATION_FAILED"
  | "CHECKPOINT_NOT_READY"
  | "INVALID_FLOW_EXECUTOR"
  | "AUDIT_RECORD_MISMATCH"
  | "DELIVERY_FLOW_ID_MISMATCH"
  | "DELIVERY_FLOW_NOT_FOUND"
  | "DELIVERY_FLOW_NOT_EXECUTABLE"
  | "DUPLICATE_DELIVERY_FLOW"
  | "DUPLICATE_DISCIPLINE"
  | "DISCIPLINE_NOT_FOUND"
  | "DISCIPLINE_ROOT_NOT_FOUND"
  | "UNKNOWN_PROJECT_DISCIPLINE"
  | "PROJECT_DISCIPLINE_MISMATCH"
  | "LEGACY_PROJECT_OVERLAY_PATH"
  | "DUPLICATE_PROJECT_KNOWLEDGE"
  | "PROJECT_KNOWLEDGE_DIRECTORY_MISMATCH"
  | "PROJECT_KNOWLEDGE_CONTENT_MISSING"
  | "DUPLICATE_ARTIFACT_DEFINITION"
  | "ARTIFACT_DEFINITION_NOT_FOUND"
  | "DEFINITION_NOT_FOUND"
  | "REFERENCE_NOT_FOUND"
  | "UNKNOWN_STAGE_REF"
  | "STAGE_NOT_FOUND"
  | "DUPLICATE_STAGE"
  | "BUILD_NOT_READY"
  | "PORTABILITY_VIOLATION"
  | "DUPLICATE_DISCIPLINE_STAGE_HOOK"
  | "INVALID_DISCIPLINE_AGENT"
  | "INVALID_DISCIPLINE_HOOK"
  | "DISCIPLINE_AGENT_NOT_FOUND"
  | "DISCIPLINE_SKILL_NOT_FOUND"
  | "DISCIPLINE_FILE_CONFLICT"
  | "DUPLICATE_INTEGRATION"
  | "INTEGRATION_ID_MISMATCH"
  | "INTEGRATION_SKILL_NOT_FOUND"
  | "INTEGRATION_NOT_FOUND"
  | "CONTEXT_RESOLUTION_FAILED"
  | "CONTEXT_RECEIPT_INVALID"
  | "DUPLICATE_ROLE"
  | "UNKNOWN_ROLE_REF"
  | "ROLE_NOT_FOUND"
  | "ROLE_DEFINITION_NOT_FOUND"
  | "INVALID_ROLE_DEFINITION"
  | "LEGACY_AUDIT_INVALID"
  | "LEGACY_LOCKS_PRESENT"
  | "LEGACY_RECORD_INVALID"
  | "STORAGE_LAYOUT_CONFLICT"
  | "STORAGE_MIGRATION_FAILED";

export class PdlcError extends Error {
  readonly code: PdlcErrorCode;
  readonly details?: unknown;

  constructor(code: PdlcErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = "PdlcError";
    this.code = code;
    this.details = details;
  }
}
